-- This file contains SQL statements for initializing static data and creating additional tables required by your extension.
-- It is executed during the extension installation to populate the database with necessary static data.
-- This file is optional and should be used if your extension requires specific static data or additional table setups.
-- Ensure the SQL syntax complies with TYPO3 database requirements.
